In [366]:
import numpy as np
import time
import math 

## Normal Function

In [367]:
def normal_function(x,y):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.matmul(np.matmul(np.linalg.inv(np.matmul(x_new.T,x_new)),x_new.T),y)
    return theta

## Cost Function

In [371]:
def mse(x,y,theta_hat):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    diff=np.dot(x_new,theta_hat)-y
    mse=math.sqrt(sum(diff**2)/m)
    return mse

## Batch Gradient Descent Matrix

In [ ]:
def gradient_descent(x,y,alpha):
    t=np.ones((5000,1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(500):
        diff=np.dot(x_new,theta)-y
        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
        diff_mat=diff_repeat*x_new
        theta-=alpha/m*sum(diff_mat)
#        for j in range(len(x_new)):
#            theta-=alpha/m*x_new[j]*diff[j]
    return theta

## Batch Gradient Descent Loop

In [370]:
def gradient_descent_loop(x,y,alpha,epochs):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(epochs):
        diff=np.dot(x_new,theta)-y
#        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
#        diff_mat=diff_repeat*x_new
#        theta-=alpha/m*sum(diff_mat)
        for j in range(len(x_new)):
            theta-=alpha/m*x_new[j]*diff[j]
    return theta

## Mini Batch Gradient Descent

In [372]:
def gradient_descent_loop_minibatch(x,y,alpha,epochs,batch_size):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(epochs):
        diff=np.dot(x_new,theta)-y
#        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
#        diff_mat=diff_repeat*x_new
#        theta-=alpha/m*sum(diff_mat)
        batch_index=np.random.randint(m,size=batch_size)
        for j in range(len(batch_index)):
            theta-=alpha/m*x_new[batch_index[j]]*diff[batch_index[j]]
    return theta

## Test Case One 

50000 observations; 101 features

In [384]:
epsilon=3*np.random.rand(5000)
h_theta=np.array(range(100))
x=5*np.random.rand(5000,100)
y=np.dot(x,h_theta)+epsilon+50

In [385]:
time_start=time.time()
theta_normal=normal_function(x,y)
time_end=time.time()
mse_normal=mse(x,y,theta_normal)
print('time cost',time_end-time_start,'s. The mse is', mse_normal)

time cost 0.011132955551147461 s. The mse is 0.8620659917475911


In [387]:
time_start=time.time()
theta_gradient_descent_loop=gradient_descent_loop(x,y,0.003,1000)
time_end=time.time()
mse_gradient_descent_loop=mse(x,y,theta_gradient_descent_loop)
print('time cost',time_end-time_start,'s.The mse is', mse_gradient_descent_loop)

time cost 19.74905300140381 s.The mse is 2.244101108434113


In [388]:
time_start=time.time()
theta_hat_minibatch=gradient_descent_loop_minibatch(x,y,alpha=0.003,epochs=10000,batch_size=300)
time_end=time.time()
mse_minibatch=mse(x,y,theta_hat_minibatch)
print('time cost',time_end-time_start,'s. The mse is', mse_minibatch)

time cost 15.139108180999756 s. The mse is 11.003470257982933


In [108]:
np.matmul(np.matmul(numpy.linalg.inv(np.matmul(x.T,x)),x.T),y)

array([1.13666439, 2.11810151, 3.10428909, 4.06050459, 5.13454187,
       6.14436843])

In [217]:
def gradient_descent(x,y,alpha):
    t=np.ones((5000,1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(500):
        diff=np.dot(x_new,theta)-y
        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
        diff_mat=diff_repeat*x_new
        theta-=alpha/m*sum(diff_mat)
#        for j in range(len(x_new)):
#            theta-=alpha/m*x_new[j]*diff[j]
    return theta

In [224]:
time_start=time.time()
sol_grad=gradient_descent(x,y,alpha=0.00031)
sol_grad
time_end=time.time()
print('time cost',time_end-time_start,'s')

time cost 19.5274441242218 s


In [222]:
sol_grad

array([325.86886497, 327.34977381, 374.09841286, ..., 624.35382203,
       649.62228076, 200.23867015])

In [286]:
def gradient_descent_loop(x,y,alpha,epochs):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(epochs):
        diff=np.dot(x_new,theta)-y
#        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
#        diff_mat=diff_repeat*x_new
#        theta-=alpha/m*sum(diff_mat)
        for j in range(len(x_new)):
            theta-=alpha/m*x_new[j]*diff[j]
    return theta

In [226]:
time_start=time.time()
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000315)
sol_grad_loop
time_end=time.time()
print('time cost',time_end-time_start,'s')

time cost 14.505366086959839 s


In [229]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000318)
sol_grad_loop

array([321.57151206, 323.11722226, 370.67384958, ..., 626.44756178,
       652.21589151, 199.9606717 ])

In [230]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000317)
sol_grad_loop

array([322.68428439, 324.2192951 , 371.67797429, ..., 626.76385803,
       652.46172621, 200.22500508])

In [231]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000319)
sol_grad_loop

array([305.54422507, 307.16973521, 354.76558832, ..., 611.2365041 ,
       637.30085332, 193.77033979])

In [232]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.0003195)
sol_grad_loop

array([243.34912827, 245.26562957, 292.66850324, ..., 549.52425728,
       576.55670312, 169.14802791])

In [233]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.00031975)
sol_grad_loop

array([150.22655321, 152.57599696, 199.63908821, ..., 456.72896778,
       485.18433854, 132.19343533])

In [239]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000319999)
sol_grad_loop

array([-57.67410262, -54.04611183,  -1.70943692, ..., 298.20341067,
       332.80775988,  60.46822452])

In [240]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000319985)
sol_grad_loop

array([-39.67143235, -36.12694618,  16.27885739, ..., 316.16876305,
       350.49991476,  67.61822028])

In [241]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000319988)
sol_grad_loop

array([-43.45011664, -39.88810289,  12.50319737, ..., 312.39796596,
       346.78646367,  66.11747836])

In [ ]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.000319988)
sol_grad_loop

In [242]:
sol_grad_loop=gradient_descent_loop(x,y,alpha=0.00003)
sol_grad_loop

array([477.99589379, 476.28635433, 485.02589189, ..., 517.82039489,
       515.74526764, 200.36924077])

In [266]:
epsilon=np.random.rand(1000)
h_theta=np.array((6,3))
x_2=np.random.rand(1000,2)
y_2=np.dot(x_2,h_theta)+epsilon+5

In [283]:
gradient_descent_loop(x_2,y_2,alpha=0.1)

array([5.96321487, 2.98089671, 5.5251487 ])

In [ ]:
h_theta=np.array(range(1000))

In [284]:
epsilon=np.random.rand(1000)
h_theta=np.array(range(10))
x_2=np.random.rand(1000,10)
y_2=np.dot(x_2,h_theta)+epsilon+5

In [287]:
gradient_descent_loop(x_2,y_2,alpha=0.1,epochs=1000)

array([0.01345737, 0.98599459, 1.94415261, 2.95439119, 3.97939869,
       5.04749956, 5.97127713, 6.97464609, 7.93588939, 8.96587175,
       5.62447134])

In [303]:
def gradient_descent_loop(x,y,alpha,epochs):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(epochs):
        diff=np.dot(x_new,theta)-y
#        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
#        diff_mat=diff_repeat*x_new
#        theta-=alpha/m*sum(diff_mat)
        for j in range(len(x_new)):
            theta-=alpha/m*x_new[j]*diff[j]
    return theta

In [319]:
def mse(x,y,theta_hat):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    diff=np.dot(x_new,theta_hat)-y
    mse=math.sqrt(sum(diff**2)/m)
    return mse

In [296]:
epsilon=3*np.random.rand(5000)
h_theta=np.array(range(100))
x=5*np.random.rand(5000,100)
y=np.dot(x,h_theta)+epsilon+50

In [313]:
theta_hat=gradient_descent_loop(x,y,alpha=0.003,epochs=1200)
theta_hat

array([ 0.16428276,  1.16252321,  2.12322961,  3.15829911,  4.18645924,
        5.16437619,  6.22021418,  7.19168299,  8.19790775,  9.13084629,
       10.14049501, 11.15862324, 12.11089179, 13.13137041, 14.16424439,
       15.13151319, 16.15026258, 17.15807502, 18.09271149, 19.08493472,
       20.12913151, 21.09008609, 22.1360107 , 23.14911337, 24.15389207,
       25.14821753, 26.15116787, 27.10299937, 28.11917851, 29.13782985,
       30.13803711, 31.14609695, 32.13447355, 33.14106497, 34.09505453,
       35.11760396, 36.09215233, 37.14495338, 38.17144211, 39.10646012,
       40.13721157, 41.13434536, 42.15718454, 43.16379573, 44.12435812,
       45.05086013, 46.11990581, 47.14596827, 48.08194898, 49.15494093,
       50.17299535, 51.12437992, 52.12214543, 53.13635246, 54.1549651 ,
       55.10899922, 56.10979987, 57.11330079, 58.08790636, 59.14971015,
       60.1082532 , 61.11987134, 62.15152721, 63.1128242 , 64.19348898,
       65.13454518, 66.09748163, 67.07891355, 68.04635232, 69.11

In [320]:
mse(x,y,theta_hat)

1.9995913490387127

In [324]:
mse(x,y,h_theta_new)

1.7301392791840706

In [322]:
h_theta_new=np.append(h_theta,50)

In [323]:
h_theta_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 50])

In [ ]:
theta_hat=gradient_descent_loop(x,y,alpha=0.003,epochs=1200)
theta_hat

In [ ]:
def gradient_descent_loop_minibatch(x,y,alpha,epochs,batch_size):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.ones(x_len)
    for i in range(epochs):
        diff=np.dot(x_new,theta)-y
#        diff_repeat=diff.repeat(x_len).reshape(m,x_len)
#        diff_mat=diff_repeat*x_new
#        theta-=alpha/m*sum(diff_mat)
        batch_index=np.random.randint(m,size=batch_size)
        for j in range(len(batch_index)):
            theta-=alpha/m*x_new[batch_index[j]]*diff[batch_index[j]]
    return theta

In [360]:
def normal_function(x,y):
    t=np.ones((len(x),1))
    x_new=np.append(x,t,axis=1)
    x_len=len(x_new.T)
    m=len(x_new)
    theta=np.matmul(np.matmul(np.linalg.inv(np.matmul(x_new.T,x_new)),x_new.T),y)
    return theta

In [354]:
time_start=time.time()
theta_hat_minibatch=gradient_descent_loop_minibatch(x,y,alpha=0.003,epochs=10000,batch_size=300)
time_end=time.time()
mse_minibatch=mse(x,y,theta_hat_minibatch)
print('time cost',time_end-time_start,'s. The mse is', mse_minibatch)

time cost 14.636261940002441 s. The mse is 11.682820137029758


In [362]:
time_start=time.time()
theta_hat=gradient_descent_loop(x,y,alpha=0.003,epochs=1200)
time_end=time.time()
mse_total=mse(x,y,theta_hat)
print('time cost',time_end-time_start,'s. The mse is', mse_total)

time cost 23.58353900909424 s. The mse is 1.9995913490387127


In [357]:
theta_normal=np.matmul(np.matmul(np.linalg.inv(np.matmul(x.T,x)),x.T),y)

In [364]:
time_start=time.time()
theta_normal=normal_function(x,y)
time_end=time.time()
mse_normal=mse(x,y,theta_normal)
print('time cost',time_end-time_start,'s. The mse is', mse_normal)

time cost 0.00960993766784668 s. The mse is 0.8515923705881321
